# Generated by Django 3.2.8 on 2021-10-10 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('type', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('distance', models.FloatField()),
                ('moving_time', models.PositiveIntegerField()),
                ('total_elevation_gain', models.FloatField()),
                ('average_speed', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('start_location', models.TextField()),
                ('detail', models.JSONField()),
                ('streams', models.JSONField()),
                ('athlete_id', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
