# Generated by Django 3.2.8 on 2021-10-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='timezone',
            field=models.TextField(default='Asia/Ho_Chi_Minh'),
            preserve_default=False,
        ),
    ]
