# Generated by Django 3.2.8 on 2021-10-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='initial_rotation',
            field=models.IntegerField(default=-10),
        ),
    ]
