# Generated by Django 3.2.8 on 2021-10-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activity_initial_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='analytics',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
