# Generated by Django 3.2.8 on 2021-11-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20211018_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='hide_map',
            field=models.BooleanField(default=False),
        ),
    ]
