# Generated by Django 3.2.8 on 2021-11-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='hide_fitness',
            field=models.BooleanField(default=False),
        ),
    ]
